### ISSUE TITLE
Equations not rendering in Vignettes

### ISSUE THREAD

**Issue by lebebr01** [ellessenne/rsimsum#2]
Issue for [JOSS review](https://github.com/openjournals/joss-reviews/issues/739).

The equations are currently not rendering in any of the vignettes. This occurred when I used `install.packages("rsimsum")` and installing directly from GitHub with `devtools::install_github("ellessenne/rsimsum", build_vignettes = TRUE)`.

This makes the introduction vignette particularly difficult and also makes it difficult to understand the computations the package does without users digging into the code.

**Comment by ellessenne** [comment]
Hi,
I can't seem to reproduce this problem - I tried on several machines (macOS High Sierra, Windows 7, Windows 10), and it generally works fine for me.
Does the problem occur within RStudio? I sometimes find the RStudio viewer a bit fiddly myself, as sometimes css and js are not loaded properly. If so, could you try the following on the plain R console (not within RStudio):

```r
vignette(topic = "introduction", package = "rsimsum")
```

Does MathJax load the equations this way?

**Comment by lebebr01** [comment]
That is the issue, the equations do not render in RStudio. That is good to know, I wasn't aware of that limitation. 

This issue may be worth mentioning in the README as RStudio is becoming common.

**Comment by ellessenne** [comment]
I know, unfortunately there is nothing I can do about it - there is an open issue with RStudio [here](https://github.com/rstudio/rstudio/issues/2253), hopefully this should be resolved soon!
In the meanwhile, I can sure add a little "disclaimer" within the README file!
