### ISSUE TITLE
Clarifications within Introduction vignette

### ISSUE THREAD

**Issue by lebebr01** [ellessenne/rsimsum#3]
Issue for [JOSS review](https://github.com/openjournals/joss-reviews/issues/739).

Below are some items I feel would benefit from some additional clarification in the vignette to ensure users are comfortable with using the `simsum` function and understanding the output.

- [ ] The data from the first example are described well, however there was very little discussion of how to use the `simsum` function except for showing the function used with the MIsim data. For example, how do we know the true value is 0.5 or -0.5, why is `ref = "CC"` and not specified in the second example, etc?
- [ ] I found the discussion of the output from `simsum` to be relatively brief which leaves a lot of burden on the user to understand the output coming from the function with no discussion. I believe some discussion of the output would improve the user experience and confidence in understanding how to interpret the specific statistics.
- [ ] I wonder if a table would be useful for what the values in the "stat" column represent after running the `get_data` function. 
- [ ] From the vignette and `simsum` documentation, it is not completely clear to me the difference between the `methodvar` and `by` arguments. I believe the main distinction seems to be within vs between simulation conditions (this was gathered from the JOSS paper), however from the documentation itself, I was unsure.

**Comment by ellessenne** [comment]
Hello,
I pushed some updates to improve documentation and the introductory vignette, hopefully the points you highlighted are more clear now!
I also added a `description` argument to each `get_data` method: if set to `TRUE`, an additional column with a description of each summary statistic is attached to the `data.frame` return by the function.
What do you think about these changes?

**Comment by lebebr01** [comment]
I like the changes. I find the additional clarification in the introduction vignette and documentation to be very helpful and I can imagine would be useful for users new to simulation studies.

Secondly, I really like the description argument to the `get_data` function. Very useful and unique solution, better than referencing a table in the documentation.
