### ISSUE TITLE
Plotting functions

### ISSUE THREAD

**Issue by lebebr01** [ellessenne/rsimsum#4]
Issue for [JOSS review](https://github.com/openjournals/joss-reviews/issues/739).

A few questions/clarifications I had regarding the plotting output and functions.

- [ ] The `pattern` and `zip` plot functions do not need to specify the `by` argument, but the other plotting functions do. Is it possible to reuse the `by` argument from the `simsum` output object? This would be more consistent across the plotting functions and I also think would be easier for users to not have to reuse the same arguments across functions.
- [ ] Is the sample size order in the figures customizable? In some of the figures from the plotting vignette they go from smallest to largest, but others go from largest to smallest. It'd be great if this could be customizable, otherwise being consistent would be second best.
- [ ] Specific to the plotting vignette. I understand what "multiple estimands" means for the `multsimsum` function, however to ensure the vignette is more approachable to a variety of audiences, I would consider adding synonyms for the word estimands used in other fields.

**Comment by ellessenne** [comment]
Hello,
here are my comments point by point:
1. `pattern` and `zip` plot estimated values and standard errors directly, while the remaining plotting functions plot summary statistics; therefore, I thought it was more interesting to plot every combination of data-generating mechanisms and methods for the former, while requesting to manually specify `by` factors manually for the latter. I am not sure inferring `by` factors would be wise, as (for instance) Monte Carlo simulation studies with several data-generating mechanisms would return plots that are too messy to be useful. Regardless, it is possible to call functions such as `lolly` and `forest` without specifying any `by` factor, and a relevant warning will be thrown suggesting to manually applying faceting as desired to obtain a sensible plot;
2. All values of data-generating mechanisms are by default stored as strings - I will add a section to the plotting vignette on how to manually rearrange and customise the appearance of plots;
3. Thanks, I will try to clarify - any suggestion regarding synonyms?

**Comment by lebebr01** [comment]
These comments make sense to me. Thanks for articulating. 

Regarding 3, perhaps parameter or theta would be a synonyms?

**Comment by ellessenne** [comment]
Thanks, I am adding "parameters" to the vignette and an additional line explaining what it means in that specific example!
