### ISSUE TITLE
Statement of Need

### ISSUE THREAD

**Issue by lebebr01** [ellessenne/rsimsum#5]
Issue for [JOSS review](https://github.com/openjournals/joss-reviews/issues/739).

I found the statement of need well articulated in the JOSS paper itself, however I wonder if this would be useful to also articulate in the README of the software repository. Users are probably more likely to see the package README first compared to the JOSS paper, therefore being more clear about the uses and goals of the package in the README is beneficial in my mind.

**Comment by ellessenne** [comment]
Hello, I just updated the README file on GitHub by adding bits and bobs from the JOSS paper!
