### ISSUE TITLE
Input limits of confidence interval

### ISSUE THREAD

**Issue by MvanSmeden** [ellessenne/rsimsum#6]
It would be great if the rsimsum function could handle the limits of a confidence interval as input rather than "only" SE.

**Comment by ellessenne** [comment]
Hi @MvanSmeden! 
I have been looking into this issue, and I would like to clarify something before going ahead and pushing my changes.
At the moment, I implemented custom confidence intervals by simply passing a vector `ci.limits` of length two with the lower and upper limit of a confidence interval. 
However, coverage would then be (using pseudo-code)
```r
coverage = mean(true.value >= ci.limits[1] & true.value <= ci.limits[2]) 
```
which looks odd to me, as both `true.value` and `ci.limits` are provided by the user. 
Is this what you would like to do or am I misunderstanding something?
Thanks,

Alessandro

**Comment by MvanSmeden** [comment]
Hi Alessandro,

Thank you so much for taking the time to work on this.
Yes, this is exactly it (although I usually try to speed it up a bit by true %between% c(l_limit, u_limit)  (package dplyr or datatable I think)
The only difference I guess is that the user now has to give 3 values (true,lb,up) instead of 2 (true,est se).

Maarten

**Comment by ellessenne** [comment]
Thanks for the feedback, I just pushed my changes to GitHub.
Could you give it a go by installing the most up-to-date version with:
```r
devtools::install_github("ellessenne/rsimsum")
```

Thanks!
